DROP USER zgf_domainds CASCADE;

CREATE USER zgf_domainds IDENTIFIED BY zgf_domainds
 DEFAULT TABLESPACE "USERS"
 TEMPORARY TABLESPACE "TEMP"
 QUOTA UNLIMITED ON "USERS";

GRANT "CONNECT" TO zgf_domainds WITH ADMIN OPTION;
GRANT "DBA" TO zgf_domainds WITH ADMIN OPTION;
ALTER USER zgf_domainds DEFAULT ROLE "CONNECT", "DBA";