delete from vt_jb_users where user_name = 'SampleUser1';
delete from vt_jb_users where user_name = 'SampleUser2';
delete from vt_jb_users where user_name = 'SampleUser3';
delete from vt_jb_users where user_name = 'SampleUser4';
delete from vt_jb_users where user_name = 'SampleUser5';
delete from vt_jb_users where user_name = 'SampleUser6';
delete from vt_jb_users where user_name = 'SampleUser7';
delete from vt_jb_users where user_name = 'SampleUser8';
delete from vt_jb_users where user_name = 'SampleUser9';
delete from vt_jb_users where user_name = 'SampleUser10';
delete from vt_jb_users where user_name = 'manager1';
delete from vt_jb_users where user_name = 'manager2';
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser1', 'sample','SampleUser1','SampleUser1','SampleUser1',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser2', 'sample','SampleUser2','SampleUser2','SampleUser2',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser3', 'sample','SampleUser3','SampleUser3','SampleUser3',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser4', 'sample','SampleUser4','SampleUser4','SampleUser4',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser5', 'sample','SampleUser5','SampleUser5','SampleUser5',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser6', 'sample','SampleUser6','SampleUser6','SampleUser6',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser7', 'sample','SampleUser7','SampleUser7','SampleUser7',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser8', 'sample','SampleUser8','SampleUser8','SampleUser8',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser9', 'sample','SampleUser9','SampleUser9','SampleUser9',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('SampleUser10', 'sample','SampleUser10','SampleUser10','SampleUser10',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('manager1', 'manager1','manager1','manager1','manager1',1,'');
insert into vt_jb_users (user_name, password, surname, given_name, full_name, tenant_id, sandbox_id) values ('manager2', 'manager2','manager2','manager2','manager2',1,'');
commit;
