delete from vt_jb_users where user_name = 'SampleUser1';
delete from vt_jb_users where user_name = 'SampleUser2';
delete from vt_jb_users where user_name = 'SampleUser3';
delete from vt_jb_users where user_name = 'SampleUser4';
delete from vt_jb_users where user_name = 'SampleUser5';
delete from vt_jb_users where user_name = 'SampleUser6';
delete from vt_jb_users where user_name = 'manager1';
delete from vt_jb_users where user_name = 'manager2';
delete from vt_jb_users where user_name = 'subordinate1';
delete from vt_jb_users where user_name = 'subordinate2';
delete from vt_jb_users where user_name = 'workgroup1Manager';
delete from vt_jb_users where user_name = 'workgroup2Manager';
delete from vt_jb_users where user_name = 'workgroup3Manager';
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'SampleUser1', 'sample','SampleUser1','SampleUser1','SampleUser1',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'SampleUser2', 'sample','SampleUser2','SampleUser2','SampleUser2',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'SampleUser3', 'sample','SampleUser3','SampleUser3','SampleUser3',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'SampleUser4', 'sample','SampleUser4','SampleUser4','SampleUser4',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'SampleUser5', 'sample','SampleUser5','SampleUser5','SampleUser5',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'SampleUser6', 'sample','SampleUser6','SampleUser6','SampleUser6',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'manager1', 'manager1','manager1','manager1','manager1',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'manager2', 'manager2','manager2','manager2','manager2',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'subordinate1', 'subordinate1','subordinate1','subordinate1','subordinate1',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'subordinate2', 'subordinate2','subordinate2','subordinate2','subordinate2',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'workgroup1Manager', 'manager','workgroup1Manager','workgroup1Manager','workgroup1Manager',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'workgroup2Manager', 'manager','workgroup2Manager','workgroup2Manager','workgroup2Manager',1,'');
insert into vt_jb_users values (vt_jb_sequence.NEXTVAL, 'workgroup3Manager', 'manager','workgroup3Manager','workgroup3Manager','workgroup3Manager',1,'');
-- delete from vt_dr_role_type where name = 'Manager';
-- delete from vt_dr_role_type where name = 'GenericManager';
-- delete from vt_dr_role_type where name = 'Subordinate';
-- insert into vt_dr_role_type values (vt_dr_sequence.NEXTVAL,'Manager','com.vitria.workflow.role.dynamic.ManagerDynamicRoleProvider',null);
-- insert into vt_dr_role_type values (vt_dr_sequence.NEXTVAL,'GenericManager','com.vitria.workflow.role.dynamic.GenericManagerDynamicRoleProvider',null);
-- insert into vt_dr_role_type values (vt_dr_sequence.NEXTVAL,'Subordinate','com.vitria.workflow.role.dynamic.SubordinateDynamicRoleProvider',null);
commit;
