call al rn -2\(kbat##ktar##btenv##Config) ~ ar "'C:\Users\Chudy'" "C:\Users\gzhou"
call al rn -2\(kbat##ktar##btenv##Config) ~ ar "'C:\\Users\\Chudy'" "C:\\Users\\gzhou"
call al rn -2\(kbat##ktar##btenv##Config) ~ ar "'D:\soft\typeandrun'" "D:\Workflow-G\software\typeandrun"
call al rn -2\(kbat##ktar##btenv##Config) ~ ar "'D:\\soft\\typeandrun'" "D:\\Workflow-G\\software\\typeandrun"
call al rn -2\(kbat##ktar##btenv##Config) ~ ar "'G:\huazhi'" "H:\huazhi"
call al rn -2/(.bat##.java) af Uedit\x86 ar "'C:\Program Files'" "C:\Program Files (x86)"
call al rn -2/(.bat##.java) af Uedit\x86 ar "'C:\\Program Files'" "C:\\Program Files (x86)"
call al rn -2/(.bat##.java) af chrome\x86 ar "'C:\Program Files'" "C:\Program Files (x86)"
call al rn -2/(.bat##.java) af iexplore\x86 ar "'C:\Program Files'" "C:\Program Files (x86)"
call al rn\Test-2.java ~ af "'//import org'\org.w3c\org.xml" c ar "'//import org'" "import org"
call al rn\Test-2.java ~ af "'//import org'\org.w3c\org.xml" c ar "'//import org'" "import org"