call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "C:\Users\gzhou" "C:\Users\Chudy"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "C:\Program Files (x86)\\" "C:\Program Files\\"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "E:\zhouguifang\Software\Network\sterm\STERM2220 Beta\STerm.exe" "D:\soft\sterm\STERM2220 Beta\STerm.exe"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "C:\Users\Chudy\AppData\Roaming\Baidu\BaiduYunGuanjia\BaiduYunGuanjia.exe" "C:\Users\Chudy\AppData\Roaming\baidu\BaiduYunGuanjia\BaiduYunGuanjia.exe"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "D:\Workflow-G\software\eclipse\eclipse-4.4\eclipse\eclipse.exe|-clean -vmargs -Xmx1024M -XX:PermSize=128M -XX:MaxPermSize=512M" "D:\soft\eclipse\eclipse\eclipse.exe|-clean -vmargs -Xmx768M -XX:PermSize=128M -XX:MaxPermSize=384M"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "D:\Workflow-G\software\EasyMeeting\InletexEMC.exe" "D:\soft\easymeeting\InletexEMC.exe"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "hzu|H:\huazhi" "hzu|G:\huazhi"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "up|H:" "up|G:"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "mv|E:\movie" "mv|D:\movie"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "D:\Workflow-G\software\mysql\MySQL GUI Tools 5.0\MySQLAdministrator.exe" "D:\soft\mysql\MySQL GUI Tools 5.0\MySQLAdministrator.exe"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "pf|C:\Program Files (x86)" "pf|C:\Program Files"
call grgbk "C:\Users\Chudy\Desktop\rename\Config-2.ini" "D:\Workflow-G\software\typeandrun" "D:\soft\typeandrun"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "D:\\Workflow-G\\software\\typeandrun" "D:\\soft\\typeandrun"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "http://localhost:18080/fms" "http://localhost:8080/fms"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "C:\Program Files\Maxthon\Bin\Maxthon.exe" "C:\Program Files (x86)\Maxthon\Bin\Maxthon.exe"
