call al rn -2 ar "C:\Users\Chudy" "C:\Users\gzhou"
call al rn -2 ar "C:\\Users\\Chudy" "C:\\Users\\gzhou"
call al rn -2 ar "D:\soft\typeandrun" "D:\Workflow-G\software\typeandrun"
call al rn -2 ar "D:\\soft\\typeandrun" "D:\\Workflow-G\\software\\typeandrun"
call al rn -2 ar "G:\huazhi" "H:\huazhi"
call al rn\Test-2.java ar "'//import org'" "import org"