call svn add C:\workspace\buildtemp\files\bat\bpqdir.bat
call svn add C:\workspace\buildtemp\files\bat\mergeju.bat
call svn add C:\workspace\buildtemp\files\bat\mergejubuild.bat
call svn add C:\workspace\buildtemp\files\bat\mergejubw.bat
call svn add C:\workspace\buildtemp\files\bat\mergejuesms.bat
call svn add C:\workspace\buildtemp\files\bat\mergejum3o.bat
call svn add C:\workspace\buildtemp\files\bat\mergejuopbook.bat
call svn add C:\workspace\buildtemp\files\bat\mergejushared.bat
call svn add C:\workspace\buildtemp\files\bat\mergejusuites.bat
call svn add C:\workspace\buildtemp\files\bat\mergeopbook.bat
call svn add C:\workspace\buildtemp\files\bat\nsf.bat
call svn add C:\workspace\buildtemp\files\bat\sp.bat
call svn add C:\workspace\buildtemp\files\bat\swapps32b.bat
call svn add C:\workspace\buildtemp\files\bat\swbapps32b.bat
call svn add C:\workspace\buildtemp\files\bat\swbpq.bat
call svn add C:\workspace\buildtemp\files\bat\swpq.bat
call svn add C:\workspace\buildtemp\files\bat\udfupdateversion.bat
call svn add C:\workspace\buildtemp\files\bat\upv.bat
