call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "C:\Users\Chudy" "C:\Users\gzhou"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "C:\Program Files\\" "C:\Program Files (x86)\\"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "D:\soft\sterm\STERM2220 Beta\STerm.exe" "E:\zhouguifang\Software\Network\sterm\STERM2220 Beta\STerm.exe"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "C:\Users\gzhou\AppData\Roaming\Baidu\BaiduYunGuanjia\BaiduYunGuanjia.exe" "C:\Users\gzhou\AppData\Roaming\baidu\BaiduYunGuanjia\BaiduYunGuanjia.exe"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "D:\soft\eclipse\eclipse\eclipse.exe|-clean -vmargs -Xmx768M -XX:PermSize=128M -XX:MaxPermSize=384M" "D:\Workflow-G\software\eclipse\eclipse-4.4\eclipse\eclipse.exe|-clean -vmargs -Xmx1024M -XX:PermSize=128M -XX:MaxPermSize=512M"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "D:\soft\easymeeting\InletexEMC.exe" "D:\Workflow-G\software\EasyMeeting\InletexEMC.exe"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "hzu|G:\huazhi" "hzu|H:\huazhi"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "up|G:" "up|H:"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "mv|D:\movie" "mv|E:\movie"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "D:\soft\mysql\MySQL GUI Tools 5.0\MySQLAdministrator.exe" "D:\Workflow-G\software\mysql\MySQL GUI Tools 5.0\MySQLAdministrator.exe"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "pf|C:\Program Files (x86)" "pf|C:\Program Files"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "pfj|C:\Program Files (x86)" "pfj|C:\Program Files"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "jdk|C:\Program Files (x86)" "jdk|C:\Program Files"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "D:\soft\typeandrun" "D:\Workflow-G\software\typeandrun"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "D:\\soft\\typeandrun" "D:\\Workflow-G\\software\\typeandrun"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "http://localhost:8080/fms" "http://localhost:18080/fms"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "C:\Program Files (x86)\Maxthon\Bin\Maxthon.exe" "C:\Program Files\Maxthon\Bin\Maxthon.exe"
call grgbk "C:\Users\gzhou\Desktop\rename\Config-2.ini" "localhost" "10.101.3.73"