create table HILOSEQUENCES (SEQUENCENAME varchar(50) not null,HIGHVALUES integer not null,constraint hilo_pk primary key (SEQUENCENAME));
create table TIMERS (  TIMERID VARCHAR2(50) NOT NULL, TARGETID VARCHAR2(50) NOT NULL, INITIALDATE TIMESTAMP NOT NULL, INTERVAL NUMBER(19), INSTANCEPK BLOB, INFO BLOB, CONSTRAINT TIMERS_PK PRIMARY KEY (TIMERID) );
create table JOURNAL (REVISION_ID number(20,0) NOT NULL, JOURNAL_ID varchar(255), PRODUCER_ID varchar(255), REVISION_DATA blob);
create unique index JOURNAL_IDX on JOURNAL (REVISION_ID);
create table GLOBAL_REVISION (REVISION_ID number(20,0) NOT NULL);
create unique index GLOBAL_REVISION_IDX on GLOBAL_REVISION (REVISION_ID);
insert into GLOBAL_REVISION VALUES(0);
commit;
